import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        background: "#fcf9f8",
        surface: "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e4e2e1",
        "surface-variant": "#e4e2e1",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#40484d",
        "on-background": "#1b1c1c",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        outline: "#70787e",
        "outline-variant": "#bfc8ce",
        "surface-tint": "#136685",
        primary: "#00455d",
        "on-primary": "#ffffff",
        "primary-container": "#005e7d",
        "on-primary-container": "#92d6f9",
        "inverse-primary": "#8ccff3",
        "primary-fixed": "#c1e8ff",
        "primary-fixed-dim": "#8ccff3",
        "on-primary-fixed": "#001e2b",
        "on-primary-fixed-variant": "#004d67",
        secondary: "#815504",
        "on-secondary": "#ffffff",
        "secondary-container": "#fdc26c",
        "on-secondary-container": "#774e00",
        "secondary-fixed": "#ffddb2",
        "secondary-fixed-dim": "#f7bc67",
        "on-secondary-fixed": "#291800",
        "on-secondary-fixed-variant": "#624000",
        tertiary: "#3f403f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#565756",
        "on-tertiary-container": "#cdcdcb",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "panel-gap": "1px",
        "sidebar-width": "300px",
        "inspector-width": "360px",
        "element-gap": "0.75rem",
        "section-padding": "1.5rem",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        display: ["Geist", "system-ui", "sans-serif"],
      },
      fontSize: {
        "data-label": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        display: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
